//! Tests for the `min-publish-age` feature (RFC 3923).

use cargo_test_support::compare::assert_e2e;
use cargo_test_support::project;
use cargo_test_support::registry::Package;
use cargo_test_support::str;

use crate::prelude::*;

/// Mocked "now" for deterministic publish-age comparisons.
const NOW: &str = "2006-08-08T00:00:00Z";

fn publish_packages() {
    // 14 days before `NOW`
    Package::new("bar", "1.0.0")
        .pubtime("2006-07-25T00:00:00Z")
        .publish();
    // 2 days before `NOW`
    Package::new("bar", "1.1.0")
        .pubtime("2006-08-06T00:00:00Z")
        .publish();
}

#[cargo_test]
fn feature_gated() {
    publish_packages();

    let p = project()
        .file(
            "Cargo.toml",
            r#"
                [package]
                name = "foo"
                edition = "2021"

                [dependencies]
                bar = "1.0"
            "#,
        )
        .file(
            ".cargo/config.toml",
            r#"
                [registry]
                global-min-publish-age = "7 days"
            "#,
        )
        .file("src/lib.rs", "")
        .build();

    p.cargo("generate-lockfile")
        .masquerade_as_nightly_cargo(&["min-publish-age"])
        .env("__CARGO_TEST_INVOCATION_TIME", NOW)
        .with_stderr_data(str![[r#"
[UPDATING] `dummy-registry` index
[LOCKING] 1 package to latest compatible version

"#]])
        .run();

    assert_e2e().eq(
        p.read_lockfile(),
        str![[r##"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "bar"
version = "1.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2216902cacb5611f65e00da63d917a6b9f4dbb10ddc39ee24c853322ab44b041"

[[package]]
name = "foo"
version = "0.0.0"
dependencies = [
 "bar",
]

"##]],
    );
}

#[cargo_test]
fn feature_gated_env() {
    publish_packages();

    let p = project()
        .file(
            "Cargo.toml",
            r#"
                [package]
                name = "foo"
                edition = "2021"

                [dependencies]
                bar = "1.0"
            "#,
        )
        .file("src/lib.rs", "")
        .build();

    p.cargo("generate-lockfile")
        .env("CARGO_REGISTRY_GLOBAL_MIN_PUBLISH_AGE", "7 days")
        .masquerade_as_nightly_cargo(&["min-publish-age"])
        .env("__CARGO_TEST_INVOCATION_TIME", NOW)
        .with_stderr_data(str![[r#"
[UPDATING] `dummy-registry` index
[LOCKING] 1 package to latest compatible version

"#]])
        .run();

    assert_e2e().eq(
        p.read_lockfile(),
        str![[r##"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "bar"
version = "1.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2216902cacb5611f65e00da63d917a6b9f4dbb10ddc39ee24c853322ab44b041"

[[package]]
name = "foo"
version = "0.0.0"
dependencies = [
 "bar",
]

"##]],
    );
}

#[cargo_test]
fn warns_on_resolver_config_without_flag() {
    publish_packages();

    let p = project()
        .file(
            "Cargo.toml",
            r#"
                [package]
                name = "foo"
                edition = "2021"

                [dependencies]
                bar = "1.0"
            "#,
        )
        .file(
            ".cargo/config.toml",
            r#"
                [resolver]
                incompatible-publish-age = "deny"
            "#,
        )
        .file("src/lib.rs", "")
        .build();

    p.cargo("generate-lockfile")
        .with_stderr_data(str![[r#"
[WARNING] unused config key `resolver.incompatible-publish-age` in `[ROOT]/foo/.cargo/config.toml`
[UPDATING] `dummy-registry` index
[LOCKING] 1 package to latest compatible version

"#]])
        .run();
}
