(function() {var implementors = {};
implementors["cargo"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='cargo/core/package_id/enum.PackageIdError.html' title='cargo::core::package_id::PackageIdError'>PackageIdError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='cargo/util/errors/trait.CargoError.html' title='cargo::util::errors::CargoError'>CargoError</a>&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='cargo/util/errors/struct.ProcessError.html' title='cargo::util::errors::ProcessError'>ProcessError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='cargo/util/errors/struct.CargoTestError.html' title='cargo::util::errors::CargoTestError'>CargoTestError</a>","impl&lt;E:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='cargo/util/errors/struct.Human.html' title='cargo::util::errors::Human'>Human</a>&lt;E&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='struct' href='cargo/util/errors/struct.CliError.html' title='cargo::util::errors::CliError'>CliError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
