(function() {var implementors = {};
implementors["cargo"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='cargo/core/dependency/enum.Kind.html' title='cargo::core::dependency::Kind'>Kind</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='cargo/core/resolver/enum.Method.html' title='cargo::core::resolver::Method'>Method</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='cargo/core/shell/enum.Verbosity.html' title='cargo::core::shell::Verbosity'>Verbosity</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='cargo/core/shell/enum.ColorConfig.html' title='cargo::core::shell::ColorConfig'>ColorConfig</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='cargo/core/shell/struct.ShellConfig.html' title='cargo::core::shell::ShellConfig'>ShellConfig</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='cargo/ops/enum.CompileMode.html' title='cargo::ops::CompileMode'>CompileMode</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='cargo/ops/enum.VersionControl.html' title='cargo::ops::VersionControl'>VersionControl</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='cargo/ops/struct.Unit.html' title='cargo::ops::Unit'>Unit</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='cargo/ops/struct.ProcessEngine.html' title='cargo::ops::ProcessEngine'>ProcessEngine</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='cargo/ops/enum.Kind.html' title='cargo::ops::Kind'>Kind</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='cargo/util/config/enum.Location.html' title='cargo::util::config::Location'>Location</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='cargo/util/enum.Freshness.html' title='cargo::util::Freshness'>Freshness</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
