[package]
name = "xtask-lint-docs"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
cargo.workspace = true
clap.workspace = true
itertools.workspace = true

[lints]
workspace = true
