= cargo-install(1)
:idprefix: cargo_install_
:doctype: manpage
:actionverb: Install

== NAME

cargo-install - Build and install a Rust binary

== SYNOPSIS

[%hardbreaks]
`cargo install [_OPTIONS_] _CRATE_...`
`cargo install [_OPTIONS_] --path _PATH_`
`cargo install [_OPTIONS_] --git _URL_ [_CRATE_...]`
`cargo install [_OPTIONS_] --list`

== DESCRIPTION

This command manages Cargo's local set of installed binary crates. Only
packages which have executable `\[[bin]]` or `\[[example]]` targets can be
installed, and all executables are installed into the installation root's
`bin` folder.

include::description-install-root.adoc[]

There are multiple sources from which a crate can be installed. The default
location is crates.io but the `--git`, `--path`, and `--registry` flags can
change this source. If the source contains more than one package (such as
crates.io or a git repository with multiple crates) the _CRATE_ argument is
required to indicate which crate should be installed.

Crates from crates.io can optionally specify the version they wish to install
via the `--version` flags, and similarly packages from git repositories can
optionally specify the branch, tag, or revision that should be installed. If a
crate has multiple binaries, the `--bin` argument can selectively install only
one of them, and if you'd rather install examples the `--example` argument can
be used as well.

If the package is already installed, Cargo will reinstall it if the installed
version does not appear to be up-to-date. If any of the following values
change, then Cargo will reinstall the package:

- The package version and source.
- The set of binary names installed.
- The chosen features.
- The release mode (`--debug`).
- The target (`--target`).

Installing with `--path` will always build and install, unless there are
conflicting binaries from another package. The `--force` flag may be used to
force Cargo to always reinstall the package.

If the source is crates.io or `--git` then by default the crate will be built
in a temporary target directory. To avoid this, the target directory can be
specified by setting the `CARGO_TARGET_DIR` environment variable to a relative
path. In particular, this can be useful for caching build artifacts on
continuous integration systems.

By default, the `Cargo.lock` file that is included with the package will be
ignored. This means that Cargo will recompute which versions of dependencies
to use, possibly using newer versions that have been released since the
package was published. The `--locked` flag can be used to force Cargo to use
the packaged `Cargo.lock` file if it is available. This may be useful for
ensuring reproducible builds, to use the exact same set of dependencies that
were available when the package was published. It may also be useful if a
newer version of a dependency is published that no longer builds on your
system, or has other problems. The downside to using `--locked` is that you
will not receive any fixes or updates to any dependency. Note that Cargo did
not start publishing `Cargo.lock` files until version 1.37, which means
packages published with prior versions will not have a `Cargo.lock` file
available.

== OPTIONS

=== Install Options

*--vers* _VERSION_::
*--version* _VERSION_::
    Specify a version to install. This may be a
    linkcargo:reference/specifying-dependencies.md[version requirement], like
    `~1.2`, to have Cargo select the newest version from the given
    requirement. If the version does not have a requirement operator (such as
    `^` or `~`), then it must be in the form _MAJOR.MINOR.PATCH_, and will
    install exactly that version; it is *not* treated as a caret requirement
    like Cargo dependencies are.

*--git* _URL_::
    Git URL to install the specified crate from.

*--branch* _BRANCH_::
    Branch to use when installing from git.

*--tag* _TAG_::
    Tag to use when installing from git.

*--rev* _SHA_::
    Specific commit to use when installing from git.

*--path* _PATH_::
    Filesystem path to local crate to install.

*--list*::
    List all installed packages and their versions.

*-f*::
*--force*::
    Force overwriting existing crates or binaries. This can be used if a
    package has installed a binary with the same name as another package. This
    is also useful if something has changed on the system that you want to
    rebuild with, such as a newer version of `rustc`.

*--no-track*::
    By default, Cargo keeps track of the installed packages with a metadata
    file stored in the installation root directory. This flag tells Cargo not
    to use or create that file. With this flag, Cargo will refuse to overwrite
    any existing files unless the `--force` flag is used. This also disables
    Cargo's ability to protect against multiple concurrent invocations of
    Cargo installing at the same time.

*--bin* _NAME_...::
    Install only the specified binary.

*--bins*::
    Install all binaries.

*--example* _NAME_...::
    Install only the specified example.

*--examples*::
    Install all examples.

*--root* _DIR_::
    Directory to install packages into.

include::options-registry.adoc[]

include::options-features.adoc[]

=== Compilation Options

include::options-target-triple.adoc[]

*--debug*::
    Build with the `dev` profile instead the `release` profile.

=== Manifest Options

include::options-locked.adoc[]

=== Miscellaneous Options

include::options-jobs.adoc[]

=== Display Options

include::options-display.adoc[]

=== Common Options

include::options-common.adoc[]

include::section-environment.adoc[]

include::section-exit-status.adoc[]

== EXAMPLES

. Install or upgrade a package from crates.io:

    cargo install ripgrep

. Install or reinstall the package in the current directory:

    cargo install --path .

. View the list of installed packages:

    cargo install --list

== SEE ALSO
man:cargo[1], man:cargo-uninstall[1], man:cargo-search[1], man:cargo-publish[1]
