'\" t
.\"     Title: cargo-version
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2018-12-20
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "CARGO\-VERSION" "1" "2018-12-20" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
cargo\-version \- Show version information
.SH "SYNOPSIS"
.sp
\fBcargo version [\fIOPTIONS\fP]\fP
.SH "DESCRIPTION"
.sp
Displays the version of Cargo.
.SH "OPTIONS"
.sp
\fB\-v\fP, \fB\-\-verbose\fP
.RS 4
Display additional version information.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Display the version:
.sp
.if n .RS 4
.nf
cargo version
.fi
.if n .RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
The version is also available via flags:
.sp
.if n .RS 4
.nf
cargo \-\-version
cargo \-V
.fi
.if n .RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 3." 4.2
.\}
Display extra version information:
.sp
.if n .RS 4
.nf
cargo \-Vv
.fi
.if n .RE
.RE
.SH "SEE ALSO"
.sp
\fBcargo\fP(1)