.TH "CARGO\-LOGIN" "1" "July 2016" "The Rust package manager" "Cargo Manual"
.hy
.SH NAME
.PP
cargo\-login \- Save an API token from the registry locally
.SH SYNOPSIS
.PP
\f[I]cargo login\f[] [OPTIONS] [<TOKEN>]
.SH OPTIONS
.TP
.B \-h, \-\-help
Print this message.
.RS
.RE
.TP
.B \-\-host \f[I]HOST\f[]
Host to set the token for
.RS
.RE
.TP
.B \-v, \-\-verbose
Use verbose output.
.RS
.RE
.TP
.B \-q, \-\-quiet
No output printed to stdout.
.RS
.RE
.TP
.B \-\-color \f[I]WHEN\f[]
Coloring: auto, always, never.
.RS
.RE
.SH SEE ALSO
.PP
cargo(1), cargo\-publish(1)
.SH COPYRIGHT
.PP
This work is dual\-licensed under Apache 2.0 and MIT terms.
See \f[I]COPYRIGHT\f[] file in the cargo source distribution.
