.TH "CARGO\-PUBLISH" "1" "May 2016" "The Rust package manager" "Cargo Manual"
.hy
.SH NAME
.PP
cargo\-publish \- Upload a package to the registry.
.SH SYNOPSIS
.PP
\f[I]cargo publish\f[] [OPTIONS]
.SH DESCRIPTION
.PP
Upload a package to the registry.
.SH OPTIONS
.TP
.B \-h, \-\-help
Print this message.
.RS
.RE
.TP
.B \-\-host \f[I]HOST\f[]
Host to upload the package to.
.RS
.RE
.TP
.B \-\-host \f[I]HOST\f[]
Host to upload the package to.
.RS
.RE
.TP
.B \-\-token \f[I]TOKEN\f[]
Token to use when uploading.
.RS
.RE
.TP
.B \-\-no\-verify
Don\[aq]t verify package tarball before publish.
.RS
.RE
.TP
.B \-\-manifest\-path \f[I]PATH\f[]
Path to the manifest of the package to publish.
.RS
.RE
.TP
.B \-v, \-\-verbose
Use verbose output.
.RS
.RE
.TP
.B \-q, \-\-quiet
No output printed to stdout.
.RS
.RE
.TP
.B \-\-color \f[I]WHEN\f[]
Coloring: auto, always, never.
.RS
.RE
.SH SEE ALSO
.PP
cargo(1), cargo\-install(1), cargo\-search(1)
.SH COPYRIGHT
.PP
This work is dual\-licensed under Apache 2.0 and MIT terms.
See \f[I]COPYRIGHT\f[] file in the cargo source distribution.
